[project]
name = "shap-bounds"
version = "0.0.1"
description = "Compute certified bounds in SHAP values."
readme = "README.md"
authors = [
    { name = "David Boetius", email = "david.boetius@uni-konstanz.de" }
]
requires-python = ">=3.12"
dependencies = [
    "formalax @ file:///${PROJECT_ROOT}/dependencies/formalax",
    "jax==0.5.2",
    "jaxtyping==0.3.2",
    "numpy==2.3.2",
    "scipy==1.16.1",
]

[project.optional-dependencies]
experiments = [
    "leverageshap @ file:///${PROJECT_ROOT}/dependencies/leverageshap",
    "equinox==0.13.0",
    "optax==0.2.5",
    "shap==0.49.1",
    "torch==2.8.0",
    "torchvision==0.23.0",
    "scikit-learn==1.7.2",
    "pandas==2.3.1",
    "seaborn==0.13.2",
    "requests==2.32.4",
    "ruamel.yaml==0.18.16",
    "tqdm==4.67.1",
]
extra = ["jupyter==1.1.1","tqdm==4.67.1"]
develop = ["ruff==0.14.4"]
all = ["shap-bounds[experiments,extra,develop]"]

[build-system]
requires = ["uv_build>=0.8.6,<0.9.0"]
build-backend = "uv_build"

[tool.ruff]
indent-width = 4

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "B", "W", "I", "N", "ICN", "PT", "Q"]
ignore = ["F722"]  # jax typing
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
line-ending = "lf"
docstring-code-format = true
